### ISSUE TITLE
Homework 1 feedback

### ISSUE THREAD

**Issue by pradhanr03** [AlexChaseJones/Portfolio#1]
Great work on your homework and kudos on accomplishing the bonus points. Keep up the good work and keep exceeding our expectation. Just need a little work on indentation, but I'm sure you got this. You can refer to these indentation guidelines for future. http://www.granneman.com/webdev/coding/formatting-and-indenting-your-html/

**Comment by AlexChaseJones** [comment]
Thanks Ill be sure to pay more attention to my indention detail in the future!
